### ISSUE TITLE
I have a question regarding the code.

### ISSUE THREAD

**Issue by kiseonyu** [kaist-dmlab/Prune4Rel#13]
Is it possible to integrate this codebase with a model for missing value imputation tailored for large language models (LLMs)

**Comment by seolachoi** [comment]
Our domain is image classification, intending to correct noisy labels, so Prune4Rel may not be directly applicable to missing value imputation in large language models (LLMs). The methods are designed for different tasks—noisy label correction in classification versus imputing missing data in LLMs—so integrating the two would require significant adjustments and may not be straightforward.

Let me know if you have any further questions!
