### ISSUE TITLE
Dataset Download Instructions

### ISSUE THREAD

**Issue by ddoyoungkim** [kaist-dmlab/Prune4Rel#14]
For the used dataset, the README does not provide the actual link to download the datasets. Additionally, there are no instructions on how to organize this dataset within the directory.

**Comment by seolachoi** [comment]
Thank you for pointing this out! We did not provide direct download links for the datasets in the README, and we apologize for the oversight. 

For CIFAR-10N, CIFAR-100N, and ImageNet, you can use the appropriate modules within the code, and they have their respective download sites available on their official homepages. We recommend using these resources for a smoother setup. 

As for Clothing1M, the dataset is maintained by the original authors. You would need to contact them directly via email to obtain the download link.

Let us know if you need further assistance!
