### ISSUE TITLE
Extension for backbone

### ISSUE THREAD

**Issue by e0jun** [kaist-dmlab/Prune4Rel#4]
Hello author,
Thanks for the release of the code of your paper. I love your work.

Can I apply your work to Transformer-based backbone such as ViT?

I appreciate any help you can provide.

**Comment by seolachoi** [comment]
Hello, and thank you for your kind words! I’m glad to hear that you enjoyed the work.

Yes, it should be possible to apply our approach to Transformer-based backbones like ViT.  You may need to make some adjustments to accommodate the architectural differences, especially regarding feature extraction and layer-specific configurations.
