### ISSUE TITLE
Question for data pruning

### ISSUE THREAD

**Issue by hwany-j** [kaist-dmlab/Prune4Rel#5]
I have a conceptual question about the data pruning. To the best of my understanding, it aims to reduce the label cost, and it is similar to active learning concept. Could you explain the difference between data pruning and active learning?

**Comment by seolachoi** [comment]
Both data pruning and active learning aim to reduce labeling costs, but they work differently. 

Data pruning removes redundant or less informative labeled samples to streamline the dataset. In contrast, active learning selectively queries the most informative unlabeled samples for labeling, focusing on what the model needs next.

The key difference is that in data pruning, the dataset is pruned all at once after a warm-up phase, removing less informative samples in a single step. In contrast, active learning iteratively selects the most informative samples to label, focusing on uncertainty or diversity at each step.
