### ISSUE TITLE
Other datasets

### ISSUE THREAD

**Issue by young-eun-nam** [kaist-dmlab/Prune4Rel#9]
Hi, 

Can I use Prune4Rel for the other dataset?
Do you have any considerations for the future work?

**Comment by seolachoi** [comment]
Hi,

Yes, you can apply Prune4Rel to other datasets, but the dataset must contain some form of noisy labels, as this is central to our method. If the dataset doesn’t inherently have noisy labels, you could inject noise yourself to apply our approach.

As for future work, a consideration would be to explore how Prune4Rel can be further generalized or adapted to handle different types of noisy data across various domains.

Let me know if you have any other questions!
